Update for CI, patching and versions (#68)

diff --git a/Makefile.common b/Makefile.common
--- a/Makefile.common
+++ b/Makefile.common
@@ -1,73 +1,23 @@
+# v1.0
 
 #############################
 # global settings
 #############################
+## These should really not be changed
 SHELL := /bin/bash
-EXTRAMAKEFLAGS += --warn-undefined-variables
-MAKEFLAGS += $(EXTRAMAKEFLAGS)
+IS_TOP := $(if $(filter $(TOP),$(CURDIR)),1,0)
+IS_SINGLE := $(if $(filter 1,$(words $(MAKECMDGOALS))),1,0)
 .DEFAULT_GOAL: help
-
-#############################
-# environment detection
-#############################
-CENTOS7 := $(if $(findstring CentOS Linux release 7,$(shell cat /etc/centos-release 2>/dev/null)),1,0)
-ARMV7 := $(if $(findstring armv7l,$(shell /usr/bin/arch)),1,0)
-AARCH64 := $(if $(findstring aarch64,$(shell /usr/bin/arch)),1,0)
-ARM := $(if $(ARMV7),1,$(if $(AARCH64),1,0))
-UBUNTU24 := $(if $(findstring Ubuntu 24,$(shell lsb_release -a 2>/dev/null)),1,0)
-NUMPROC := $(shell grep -c ^processor /proc/cpuinfo)
-
-##########################################################
-## basic tools
-##########################################################
-AUTORECONF ?= autoreconf
-AUTOCONF   ?= autoconf
-AWK        ?= awk
-BASENAME   ?= basename
-CAT        ?= cat
-CMAKE      ?= $(if $(shell which cmake3),cmake3,cmake)
-CD         ?= cd
-CP         ?= cp
-CURL       ?= curl
-CUT        ?= cut
-DIFF       ?= diff
-DOCKER     ?= docker
-ECHO       ?= echo
-ENVSUBST   ?= envsubst
-EXIT       ?= exit
-FILE       ?= file
-FIND       ?= find
-GCC        ?= gcc
-GIT        ?= git
-GIT_APPLY  ?= $(GIT) apply --ignore-whitespace --ignore-space-change
-GIT_CHECK  ?= $(GIT_APPLY) --check --reverse
-GREP       ?= grep
-MKDIR      ?= mkdir
-MKDIRP     ?= mkdir -p
-MV         ?= mv
-PRINTF     ?= printf
-PYTHON     ?= $(if $(shell which python3),python3,python)
-RM         ?= rm
-RMRF       ?= rm -rf
-SED        ?= sed
-STTY       ?= stty
-STRIP      ?= strip
-SYMLINK    ?= ln -nsf
-TAIL       ?= tail
-TAR        ?= tar
-TEE        ?= tee
-TEST       ?= test
-TOUCH      ?= touch
-TR         ?= tr
-WCOUNT     ?= wc -l
-WGET       ?= wget
-XXD        ?= xxd
 
 #############################
 # variable templates
 #############################
+## these are variables and functions that can be used line functions
 
 bsg_var_blank :=
+
+bsg_var_space := $(bsg_var_blank) # end of the line
+
 define bsg_var_newline
 
 $(bsg_var_blank)
@@ -84,39 +34,18 @@ define bsg_var_user
 		)
 endef
 
+define bsg_var_upper
+	$(shell echo $(1) | tr a-z A-z)
+endef
+
+define bsg_var_lower
+	$(shell echo $(1) | tr A-Z a-z)
+endef
+
 #############################
 # function templates
 #############################
-define bsg_fn_upper
-	$(eval $@_var := $(1))
-	$(shell $(ECHO) $($@_var) | $(TR) a-z A-Z)
-endef
-
-define bsg_fn_lower
-	$(eval $@_var := $(1))
-	$(shell $(ECHO) $(1) | $(TR) A-Z a-z)
-endef
-
-define bsg_fn_mkhookdirs
-	$(eval $@_hookdirs := $(1))
-	$(eval $@_hookmatch := $(addsuffix /%,$($@_hookdirs)))
-	$(eval $@_uservars := $(call bsg_var_user))
-	$(eval $@_uppervars := $(filter $(call bsg_fn_upper,$($@_uservars)),$($@_uservars)))
-	$(eval $@_uppervals := $(foreach var,$($@_uppervars),$($(var))))
-	$(eval $@_filtered := $(filter $($@_hookmatch),$($@_uppervals)))
-	$(shell $(MKDIRP) $($@_hookdirs) $($@_filtered))
-endef
-
-define bsg_fn_disable_submodules
-	$(eval $@_submodules := $(1))
-	for t in ${$@_submodules}; do \
-	    d=$$($(ECHO) $$t | $(CUT) -d '@' -f 1); \
-	    s=$$($(ECHO) $$t | $(CUT) -d '@' -f 2); \
-	    $(ECHO) "Disabling checkout for $$d/$$s"; \
-	    $(GIT) -C $$d config --local submodule.$$s.update none; \
-	    $(GIT) -C $$d submodule sync --recursive; \
-	done
-endef
+## these can be implemented as $(call statements)
 
 define bsg_fn_default_configure
 	$(eval $@_work := $(1))
@@ -124,12 +53,13 @@ define bsg_fn_default_configure
 	$(eval $@_prefix := $(3))
 	$(eval $@_extra := $(4))
 	$(eval $@_strip := -s -Wl,--gc-sections)
-	$(CD) ${$@_src}; $(AUTOCONF) -o ./configure || true; \
-	$(CD) ${$@_work}; \
-	    CFLAGS="$(CFLAGS)" \
-	    CXXFLAGS="$(CXXFLAGS)" \
-	    LDFLAGS="${$@_strip} $(LDFLAGS)" \
-	    ${$@_src}/configure --srcdir=${$@_src} --prefix=${$@_prefix} ${$@_extra}
+	cd ${$@_src}; autoconf -o ./configure || :; \
+	cd ${$@_work}; \
+		CFLAGS="$(CFLAGS)" \
+		CXXFLAGS="$(CXXFLAGS)" \
+		LDFLAGS="${$@_strip} $(LDFLAGS)" \
+		${$@_src}/configure --srcdir=${$@_src} --prefix=${$@_prefix} ${$@_extra} || :; \
+	:;
 endef
 
 define bsg_fn_default_cmake
@@ -138,101 +68,124 @@ define bsg_fn_default_cmake
 	$(eval $@_prefix := $(3))
 	$(eval $@_extra := $(4))
 	$(eval $@_strip := -s -Wl,--gc-sections)
-	$(CMAKE) -B ${$@_work} -S ${$@_src} -DCMAKE_INSTALL_PREFIX=${$@_prefix} \
-	    -DCMAKE_BUILD_TYPE=Release \
-	    -DCMAKE_C_FLAGS="$(CFLAGS)" \
-	    -DCMAKE_CXX_FLAGS="$(CXXFLAGS)" \
-	    -DCMAKE_EXE_LINKER_FLAGS="${$@_strip} $(LDFLAGS)"
+	cmake -B ${$@_work} -S ${$@_src} -DCMAKE_INSTALL_PREFIX=${$@_prefix} \
+		-DCMAKE_BUILD_TYPE=Release \
+		-DCMAKE_C_FLAGS="$(CFLAGS)" \
+		-DCMAKE_CXX_FLAGS="$(CXXFLAGS)" \
+		-DCMAKE_EXE_LINKER_FLAGS="${$@_strip} $(LDFLAGS)"; \
+	:;
 endef
 
 define bsg_fn_strip_binaries
 	$(eval $@_install := $(1))
-	$(FIND) $($@_install) -type f -exec sh -c '\
+	find ${$@_install} -type f -exec sh -c '\
 		for file; do \
-			if $(FILE) "$$file" | $(GREP) -qE "ELF (.* )?(executable|shared)"; then \
-				$(STRIP) "$$file" >/dev/null 2>&1 || true; \
+			if file "$$file" | grep -qE "ELF (.* )?(executable|shared)"; then \
+				strip "$$file" >/dev/null 2>&1 || :; \
 			fi; \
 	done \
-	' sh {} +
-endef
-
-define bsg_fn_info
-	$(eval $@_msg = $(1))
-	$(eval $@_prefix = "BSG-INFO: ")
-	$(ECHO) "$($@_prefix) $($@_msg)"
-endef
-
-define bsg_fn_warn
-	$(eval $@_msg = $(1))
-	$(eval $@_prefix = "BSG-WARN: ")
-	$(ECHO) "$($@_prefix) $($@_msg)"
-endef
-
-define bsg_fn_error
-	$(eval $@_msg = $(1))
-	$(eval $@_prefix = "BSG-ERROR: ")
-	$(ECHO) "$($@_prefix) $($@_msg)"
+	' sh {} +; \
+	:;
 endef
 
 #############################
-# target templates
+# templates
 #############################
+## these can be implemented as $(eval $(call statements))
 
 define bsg_tgt_build_tag
-	$(eval MAKEFLAGS := $(filter-out $(EXTRAMAKEFLAGS),$(MAKEFLAGS)))
 	$(eval name := $(1))
 	$(eval src_dir := $(2))
 	$(eval touch_dir := $(3))
 	$(eval patch_dir := $(4))
 	$(eval work_dir := $(5))
 	$(eval tag := $(6))
-	# patch targets
+	$(eval checkout_tag := $(touch_dir)/$(name).checkout.$(tag))
+	$(eval checkout_target := checkout.$(name))
+	$(eval uncheckout_target := un$(checkout_target))
+	$(eval recheckout_target := re$(checkout_target))
 	$(eval patch_tag := $(touch_dir)/$(name).patch.$(tag))
 	$(eval patch_target := patch.$(name))
-	$(eval repatch_target := repatch.$(name))
-	# build targets
+	$(eval unpatch_target := un$(patch_target))
+	$(eval repatch_target := re$(patch_target))
 	$(eval build_tag := $(touch_dir)/$(name).build.$(tag))
 	$(eval build_target := build.$(name))
-	$(eval rebuild_target := rebuild.$(name))
+	$(eval unbuild_target := un$(build_target))
+	$(eval rebuild_target := re$(build_target))
 	$(eval internal_target := $(work_dir)/$(name)/.$(name)_build)
+	$(eval patch_root := $(patch_dir)/$(if $(src_dir),$(shell basename $(src_dir)),$(name)))
+	$(eval patch_files := $(shell find $(patch_root) -name "*.patch" 2>/dev/null))
+	$(eval APPLY_PATCH := git apply --ignore-whitespace --ignore-space-change)
+	$(eval REVRS_PATCH := $(APPLY_PATCH) --reverse)
+	$(eval CHECK_PATCH := $(REVRS_PATCH) --check)
+
+$(uncheckout_target): $(unpatch_target)
+	if [ -f $(src_dir)/.git ]; then \
+		git submodule --quiet deinit --force $(src_dir); \
+		git submodule --quiet init $(src_dir); \
+		git submodule --quiet sync $(src_dir); \
+	fi
+$(checkout_target): | $(checkout_tag)
+$(recheckout_target): $(uncheckout_target)
+	@rm -f $(touch_dir)/$(name).checkout.*
+	@+$(MAKE) $(checkout_tag)
+$(checkout_tag):
+	@git submodule update $(src_dir)
+	@if [ -f $(src_dir)/.git ]; then \
+		git -C $(src_dir) submodule foreach --quiet "git submodule init"; \
+		git -C $(src_dir) submodule foreach --quiet "git submodule sync"; \
+		all_submodules=$$$$(git -C $(src_dir) submodule status --recursive | awk '{print $$$$2}'); \
+		if [ -n "$$$$all_submodules" ]; then \
+			skip_patterns="$(subst $(notdir $(src_dir))/,,$(subst $(bsg_var_space),,$(foreach s,$(HOOK_DISABLE_SUBMODULES),$(s).*|)))xnomatchx"; \
+			skip_submodules=$$$$(printf "%s\n" $$$$all_submodules | grep    -E "$$$$skip_patterns"); \
+			good_submodules=$$$$(printf "%s\n" $$$$all_submodules | grep -v -E "$$$$skip_patterns"); \
+			printf "submodules skipped: %s\n" $$$$skip_submodules; \
+			printf "submodules updating: %s\n" $$$$good_submodules; \
+			printf "%s\n" "$$$$good_submodules" | while read -r s; do \
+    			git -C $(src_dir) submodule update --init --recursive "$$$$s"; \
+			done; \
+		fi; \
+	fi
+	@touch $$@
+$(unpatch_target): $(unbuild_target)
+	@$(foreach p,$(patch_files),\
+		$(REVRS_PATCH) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p))) || :;\
+		)
+	@if [ -f $(src_dir)/.git ]; then \
+		git -C $(src_dir) reset --hard --recurse-submodules; \
+		git -C $(src_dir) submodule sync --recursive; \
+	fi
 $(patch_target): | $(patch_tag)
-$(repatch_target):
-	@$(RM) -f $(touch_dir)/$(name).patch.*
-	@if [ -f $(src_dir)/.git ]; then \
-		$(GIT) submodule deinit -f $(src_dir); \
-		$(GIT) submodule init $(src_dir); \
-		$(GIT) submodule update $(src_dir); \
-	fi
+$(repatch_target): $(unpatch_target)
+	@rm -f $(touch_dir)/$(name).patch.*
 	@+$(MAKE) $(patch_tag)
-$(patch_tag):
-	@$(eval patch_root := $(patch_dir)/$(if $(src_dir),$(shell $(BASENAME) $(src_dir)),$(name)))
-	@$(eval patch_files := $(shell $(FIND) $(patch_root) -name "*.patch" 2>/dev/null))
-	@if [ -f $(src_dir)/.git ]; then \
-		$(ECHO) "Synchronizing submodules for $(name)"; \
-		$(GIT) -C $(src_dir) submodule sync --recursive; \
-		$(ECHO) "Checking out submodules for $(name)"; \
-		$(GIT) -C $(src_dir) submodule update --init --recursive; \
-	fi
-	# For some reason the bash for loop doesn't work here
-	@$(ECHO) "Applying patches $(patch_files)"
+$(patch_tag): $(checkout_tag)
+	@echo "applying patches $(patch_files)"
 	@$(foreach p,$(patch_files),\
-		$(GIT_APPLY) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
-	)
-	@$(ECHO) "Checking patches $(patch_files)"
+		$(APPLY_PATCH) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
+		)
+	@echo "Checking patches $(patch_files)"
 	@$(foreach p,$(patch_files),\
-		$(GIT_CHECK) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
-	)
-	@$(TOUCH) $$@
+		$(CHECK_PATCH) $(p) --directory $(dir $(subst $(patch_dir)/,,$(p)));\
+		)
+	@touch $$@
+$(unbuild_target):
+	@rm -rf $(work_dir)/$(name)
 $(build_target): | $(build_tag)
-$(rebuild_target):
-	@$(RMRF) $(touch_dir)/$(name).build.*
-	@$(RMRF)  $(work_dir)/$(name)
+$(rebuild_target): $(unbuild_target)
+	@rm -f $(touch_dir)/$(name).build.*
 	@+$(MAKE) $(build_tag)
 $(build_tag): | $(patch_tag)
-	@$(MKDIRP) $(work_dir)/$(name)
+	@mkdir -p $(work_dir)/$(name)
 	@+$(MAKE) $(internal_target)
-	@$(TOUCH) $$@
+	@touch $$@
 $(internal_target): $(src_dir)
+bleach::
+	@+$(MAKE) $(uncheckout_target)
+tidy::
+	@+$(MAKE) $(unpatch_target)
+clean::
+	@+$(MAKE) $(unbuild_target)
 endef
 
 define bsg_tgt_build_submodule
@@ -241,81 +194,128 @@ define bsg_tgt_build_submodule
 	$(eval touch_dir := $(3))
 	$(eval patch_dir := $(4))
 	$(eval work_dir := $(5))
-	$(eval tag := $(if $(src_dir),$(shell $(CD) $(src_dir); $(GIT) rev-parse HEAD),any))
-	$(eval $(call bsg_tgt_build_tag,$(name),$(src_dir),$(touch_dir),$(patch_dir),$(work_dir),$(tag)))
+	$(eval tag := $(if $(src_dir),$(shell git ls-files --stage $(src_dir) | awk '{print $$2}'),any))
+	$(call bsg_tgt_build_tag,$(name),$(src_dir),$(touch_dir),$(patch_dir),$(work_dir),$(tag))
 endef
 
 #############################
-# Makefile targets
+# targets
 #############################
-# Global help
+# global help
 .PHONY: help
 help: ## prints this target
-	@$(eval HELPFILTER := $(if $(findstring $(CURDIR),$(TOP)),xxxxxxxx,checkout|bleach_all))
-	@$(GREP) -h '\s##\s' $(MAKEFILE_LIST) \
-		| $(GREP) -Ev "$(HELPFILTER)" \
-		| $(AWK) 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-30s\033[0m %s\n", $$1, $$2}'
+	@$(eval HELPFILTER := $(if $(findstring $(CURDIR),$(TOP)),xxxxxxxx,checkout|bleach_all|tidy|clean|bleach))
+	@grep -h '\s##\s' $(MAKEFILE_LIST) \
+		| grep -Ev "$(HELPFILTER)" \
+		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m  %-30s\033[0m %s\n", $$1, $$2}'
 
-ifeq ($(CURDIR),$(TOP))
-# Global reset
+ifeq ($(IS_TOP),1)
+# global reset
 .PHONY: bleach_all
 bleach_all: ## wipes the whole repo clean: use with caution
-	@$(GIT) -C "$(git rev-parse --show-toplevel)" submodule deinit -f .
-	@$(GIT) -C "$(git rev-parse --show-toplevel)" clean -ffdx
+	@git stash
+	@git clean -ffdx
+	@git reset --hard
+	@git submodule foreach --recursive --quiet 'git clean -fdx'
+	@git submodule foreach --recursive --quiet 'git reset --hard'
+	@git submodule deinit -f .
 
-# Global checkout
+# global checkout
 .PHONY: checkout
+checkout: $(BSG_CADENV_DIR)
 checkout: ## checkout submodules
-	@$(call bsg_fn_mkhookdirs,$(HOOK_CHECKOUT_DIRS))
-	# Synchronize any pending updates
-	@$(GIT) submodule sync
-	@$(GIT) submodule init
-	# Disable long checkouts
-	@$(call bsg_fn_disable_submodules,$(HOOK_DISABLE_SUBMODULES))
-	# Do the checkout
-	@$(GIT) submodule update
+	@$(eval $@_hookdirs := $(HOOK_CHECKOUT_DIRS))
+	@$(eval $@_hookmatch := $(addsuffix /%,$($@_hookdirs)))
+	@$(eval $@_uservars := $(call bsg_var_user))
+	@$(eval $@_uppervars := $(filter $(call bsg_var_upper,$($@_uservars)),$($@_uservars)))
+	@$(eval $@_uppervals := $(foreach var,$($@_uppervars),$($(var))))
+	@$(eval $@_extradirs := $(filter $($@_hookmatch),$($@_uppervals)))
+	@mkdir -p ${$@_hookdirs} ${$@_extradirs}
+	@git submodule init
+	@git submodule sync
+
+# global submodule tidy
+.PHONY: tidy
+tidy:: ## tidies up submodules
+
+# global submodule bleach
+.PHONY: bleach
+bleach:: ## deinitializes submodules
+
+# global submodule bleach
+.PHONY: clean
+clean:: ## cleans submodules
+
+# stub bsg_cadenv
+%/cadenv.mk:
+	@# BSG users leverage a machine-specific cadenv
+	@#   Here, we add sourcing to get these variables as well
+	@$(eval export CADENV_URL := git@github.com:bespoke-silicon-group/bsg_cadenv)
+	@# Recursive make to include the new fragment
+	@if [ -f "$(BSG_CADENV_DIR)/cadenv.mk" ]; then \
+		echo "bsg_cadenv already exists"; \
+	elif [[ ! -z $$(git ls-remote --exit-code $${CADENV_URL} HEAD 2> /dev/null) ]]; then \
+		git clone --recurse-submodules $${CADENV_URL} $(@D); \
+	else \
+		echo "bsg_cadenv not found"; \
+		mkdir -p $(@D); \
+		touch $@; \
+	fi
+	@echo "Successfully built $@!"
+
+endif
+
+ifneq ($(IS_SINGLE),1)
+ifneq (,$(filter help,$(MAKECMDGOALS)))
+$(error help must be called as a single target)
+endif
+ifneq (,$(filter bleach_all,$(MAKECMDGOALS)))
+$(error bleach_all must be called as a single target)
+endif
+ifneq (,$(filter checkout,$(MAKECMDGOALS)))
+$(error checkout must be called as a single target)
+endif
 endif
 
 ##########################################################
 ## Cad environment
 ##########################################################
+## override if needed
+## BSG members should use bsg_cadenv, which _should_ be automatically handled by this script
+CENTOS7  ?= $(if $(findstring CentOS Linux release 7,$(shell cat /etc/centos-release 2>/dev/null)),1,0)
+ARMV7    ?= $(if $(findstring armv7l,$(shell /usr/bin/arch)),1,0)
+AARCH64  ?= $(if $(findstring aarch64,$(shell /usr/bin/arch)),1,0)
+ARM      ?= $(if $(ARMV7),1,$(if $(AARCH64),1,0))
+UBUNTU24 ?= $(if $(findstring Ubuntu 24,$(shell lsb_release -a 2>/dev/null)),1,0)
+NUMPROC  ?= $(shell grep -c ^processor /proc/cpuinfo)
 
-## Override CAD tool paths if needed
-VCS       ?= vcs
-URG       ?= urg
-VERILATOR ?= verilator
+CMAKE     ?= $(if $(shell which cmake3),cmake3,cmake)
 DC_SHELL  ?= dc_shell
-VIVADO    ?= vivado
-_DVE      ?= dve
+DOCKER    ?= docker
+DVE       ?= dve
+GCC       ?= gcc
+GXX       ?= g++
 GTKWAVE   ?= gtkwave
+PYTHON    ?= $(if $(shell which python3),python3,python)
+SURELOG   ?= surelog
+SURFER    ?= surfer
+URG       ?= urg
+VCS       ?= vcs
+VERILATOR ?= verilator
+VIVADO    ?= vivado
 YOSYS     ?= yosys
-## Specify license path if needed
+# Specify license paths if needed
 VCS_HOME        ?=
 LM_LICENSE_FILE ?=
+# Commonly needed on CentOS
+export VCS_ARCH_OVERRIDE=linux
 
-ifneq ($(MAKECMDGOALS),help)
+ifneq (,$(filter-out bleach_all help ,$(MAKECMDGOALS)))
 BSG_CADENV_DIR ?= $(TOP)/bsg_cadenv
 include $(BSG_CADENV_DIR)/cadenv.mk
-ifeq ($(CURDIR),$(TOP))
-%/cadenv.mk:
-	# BSG users leverage a machine-specific cadenv
-	#   Here, we add sourcing to get these variables as well
-	@$(eval export CADENV_URL := git@github.com:bespoke-silicon-group/bsg_cadenv)
-	# Recursive make to include the new fragment
-	@if [ -f "$(BSG_CADENV_DIR)/cadenv.mk" ]; then \
-		$(ECHO) "bsg_cadenv already exists"; \
-	elif [[ ! -z $$(git ls-remote --exit-code $${CADENV_URL} HEAD 2> /dev/null) ]]; then \
-		$(GIT) clone --recurse-submodules $${CADENV_URL} $(@D); \
-	else \
-		$(ECHO) "bsg_cadenv not found"; \
-		$(MKDIRP) $(@D); \
-		$(TOUCH) $@; \
-	fi
-	@$(ECHO) "Successfully built $@!"
-endif
 endif
 
 # Saves initial values so that we can filter them later
-# MUST BE BEFORE THE PROJECT VARIABLES
+# MUST BE LAST
 VARS_OLD := $(.VARIABLES)
 
